### ISSUE TITLE
buradaki 0 private değişkene atılabilir

### ISSUE THREAD

**Issue by cagdaspektas** [VBT-FlutterCamp/yonca_yeprem_onboard_screen_login#1]
https://github.com/VBT-FlutterCamp/yonca_yeprem_onboard_screen/blob/3d34777015e9b7243aefdbca1533e15ad7f59e08/onboard/lib/feature/onboard/view/onboard_screen.dart#L20

**Comment by YoncaYeprem** [comment]
hallettim
