### ISSUE TITLE
kartal kullanabilirsin 

### ISSUE THREAD

**Issue by cagdaspektas** [VBT-FlutterCamp/yonca_yeprem_onboard_screen_login#2]
https://github.com/VBT-FlutterCamp/yonca_yeprem_onboard_screen/blob/3d34777015e9b7243aefdbca1533e15ad7f59e08/onboard/lib/core/constants/padding_constants.dart#L4
şu classı açman efsane bundan sonra bunun yerine kartal kullanabilirsin

**Comment by YoncaYeprem** [comment]
Bu projede kalsın mı şimdilik yoksa değiştireyim mi?
@cagdaspektas

**Comment by cagdaspektas** [comment]
Şimdilik kalsın sonra değişirsin @YoncaYeprem
